name: Renew Let's Encrypt Certificate

on:
  schedule:
    - cron: '0 0 */90 * *' # Runs every 90 days
  workflow_dispatch: # Allow manual trigger

jobs:
  renew-certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Renew Certificate
      env:
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        LIGHTSAIL_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
        ROUTE53_HOSTED_ZONE_ID: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
      run: |
        python lets-encrypt-renew.py
